epochs: 20
project_name: "m5_week1"
entity: "m5-group1"
runs_path: "./runs/"
report_path: "./reports/"

optimizer:
  lr: 0.0001
  beta: 0.99
  gradient_accumulation_steps: 1
  type: "adam"
  scale_parameter: True
  relative_step: True
  warmup_init: True
  clip_threshold: True